### ISSUE TITLE
start image can cause an infinite loop of "no reset hotkey set" or "no pause hotkey set" errors to appear.

### ISSUE THREAD

**Issue by Toufool** [Toufool/AutoSplit#119]
- have a start_auto_splitter image and a reset image
- set only a split hotkey, not a reset hotkey
- threshold gets met for start_auto_splitter_image
- endless amount of "no reset hotkey has been set, but your split image folder contains a reset image" errors appear.

**Comment by Toufool** [comment]
this is fixed in dev https://github.com/Toufool/Auto-Split/commit/3cb2aa6d75394ba64125bd0bccad0d126bbb0c0a

**Comment by Avasam** [comment]
Similarly:
Create new text files, rename them as PNG like below. Start Auto Splitter. Stuck in an infinite loop of errors. Should be a simple fix. Let's ensure both are fixed.

(ignore colors, that was just part of something I sent someone to visually explain, the important part is that these are not images and there's a reset image)
![image](https://user-images.githubusercontent.com/1350584/151227618-ee064ba2-02af-4982-8c20-db8c1beb5e50.png)
