### ISSUE TITLE
Offer more Capture Methods

### ISSUE THREAD

**Issue by Avasam** [Toufool/AutoSplit#134]
Currently we have `BitBlt` and `BitBlt + PrintWindow`. I can see up to 4 possibilities that can be useful to users:

1. Desktop Duplication API through Direct3D
Fastest, but cannot record overlapping windows. About 3x faster than BitBlt and does not encounter some of the same issues according to `d3dshot`. Is also what they use. (See: https://github.com/SerpentAI/D3DShot/issues/7#issuecomment-635179457 )

2. BitBlt
Fast. Allows recording background windows (as long as they still decide to render in background).
Is what `mss` uses I believe. We already have our own implementation, but I'd like to compare performances.
In my (Avasam's) experience, it cannot properly record Hardware accelerated windows, Dolphin, etc. (fixed by PrintWindow)
> bitblt also has important problems (for [nbrochu's] use case, at least) with some graphics APIs. For example, you can't give it the handle of a window that uses OpenGL or you can't capture exclusive full screen applications, these will all fail to capture.

3. BitBlt + PrintWindow (aka Force Full Content Rendering)
Extremely slow. 10-15x slower than BitBlt based on window size. Can mess up some applications' rendering pipelines. Our current fallback from BitBlt.

4. Windows Graphics Capture API
Is only available in recent windows updates. Allows recording UWP apps. Adds a yellow border around the recorded window. Performance unknown (better than PrintWindow that's for sure). Might solve all of BitBlt issues. Is considered by `d3dshot` (https://github.com/SerpentAI/D3DShot/issues/22)
<details>
  <summary>More info here:</summary>
  
Windows Graphics Capture: https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/

winrt: https://pypi.org/project/winrt/
`from winrt.windows.graphics.capture import *`

Windows.Graphics.Capture: https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture
  
![](https://cdn.discordapp.com/attachments/567372320830783489/920772501154439218/unknown.png)
  
</details>

---

Note that d3dshot is only available for Windows 8.1+. But Windows 7 is in EOL and windows 8 is a garbage fire. We can always detect user's windows version and offer Capture methods based on that anyway. For example, `Windows Graphics Capture` may obsolete `PrintWindow`.

We could show the user a dropdown as such:
- Windows Graphics Capture (speed?, most compatible, recommended?)
- BitBlt (fast, least compatible, recommended <if WGC is not available>)
- Direct3D Desktop Duplication (fastest?, no overlapping window)
- Force Full Content Rendering (slowest, only use if nothing else works for you)

And explain the differences in detail in a tooltip. Example tooltip from Dolphin. 
![image](https://user-images.githubusercontent.com/1350584/146272753-4359acd3-06e5-4d3d-ae52-818cdb0a551f.png)

**Comment by pyorot** [comment]
idk if this has been considered anywhere but ingesting from OBS virtual cam would be a good option to avoid having to run windowed projectors and screen capture at all

**Comment by Avasam** [comment]
> idk if this has been considered anywhere but ingesting from OBS virtual cam would be a good option to avoid having to run windowed projectors and screen capture at all

Absolutely. It's something I'd like as well.

**Comment by Avasam** [comment]
> idk if this has been considered anywhere but ingesting from OBS virtual cam would be a good option to avoid having to run windowed projectors and screen capture at all

If you go to https://github.com/Toufool/Auto-Split/actions/workflows/lint-and-build.yml?query=branch%3Acamera-capture-split-cam-option , click on the latest workflow run, then scroll down to "Artefacts". You'll be able to try out this feature (work in progress)

**Comment by Avasam** [comment]
Closed by #211

**Comment by Avasam** [comment]
Closed by #211
