### ISSUE TITLE
Don't over-resize for masked images

### ISSUE THREAD

**Issue by zalgo3** [Toufool/AutoSplit#157]
Especially in the case of 1080p or higher, if the non-transparent area of the mask image used for the split is small, resizing the entire image to 320x240 will lose the information inside the mask. One idea to prevent this is to adaptively determine the target size according to the number of nonzero elements in the alpha channel of the split image. At least for the L2 norm and histogram, such a change would not affect performance since they only use information about the mask's interior.

**Comment by Avasam** [comment]
To reflect a comment I made on https://github.com/Avasam/Auto-Split/pull/45

This is a great idea, and I like your implementation in that pull request. Further improvement would be to crop the image and retarget the region if the mask allows, to reduce how much we need to shrink it. Might be a bit more complex and can be done later, I'm just mentioning it for posterity.
