### ISSUE TITLE
obs 28.0 update causing window projector to not be capturable

### ISSUE THREAD

**Issue by ArthurOudini** [Toufool/AutoSplit#160]
Hi,
OBS 28.0 released yesterday and I did the update.
The autosplitter was always watching a "window projector (source)" of the game feed. 
With 28.0 it doesn't work anymore for some reason. Had some frozen captures to start with and today it's not getting any image from there. tried both with selecting a window and with selecting an area. 

I hope it's an easy fix, feel free to reach to me on discord arthuroudini#0162

**Comment by Avasam** [comment]
Can you try out https://github.com/Avasam/Auto-Split/releases ?

**Comment by Toufool** [comment]
current workarounds for anyone looking at this:

1. don't update obs to 28 or
2. use Avasam's 2.0.0 alpha build (https://github.com/Avasam/Auto-Split/releases) and select a capture method that is NOT "BitBlt"

**Comment by ArthurOudini** [comment]
I ended up re-installing a 27.xx version of OBS to have things work.
I had no clue there is Avasam's branch, it looks super cool.
Also OBS just released 28.0.1 I wonder if they have corrected this issue. 
I'm a bit afraid of retrying, I'll post here if I do so. Thanks a lot for the answers

**Comment by Toufool** [comment]
@ArthurOudini just a heads up, alpha 5 from Avasam's branch is a bit unstable due to a change from `threading` to `asyncio`. If you want it to be a bit more stable, use alpha 4.

**Comment by ArthurOudini** [comment]
You were right, Avasam's alpha 5 is capturing the window-projector of obs 28.0.0 but it has to not be "BitBlt".
btw the UI looks very good I like it !

**Comment by eleusive** [comment]
Hi, I tried using Avasam's alpha 6 with OBS 28.0.3 and AutoSplit wasn't able to capture the window-projector (tried both a window capture using not-BitBlt and my elgato capture which doesn't have this option). The preview window will just show the first frame and remain static. Downgrading to OBS 27.x.x worked fine.

**Comment by Avasam** [comment]
@eleusive Do you only get a single frame even with Windows Graphics Capture **AND** D3D Desktop Duplication?

Also just for personal ref, using `LearningModelDevice` may be problematic, I'll go back to using it at backup https://github.com/pywinrt/python-winsdk/issues/11#issuecomment-1315345318
