### ISSUE TITLE
Easy IDirect3DDevice Fix

### ISSUE THREAD

**Issue by Algomancer** [Toufool/AutoSplit#175]
Woops, didn't notice there was a 2.0 branch here, posted this on a fork.

Great project.
Just was floating around and noticed you are using the media capture work around for initialising a IDirect3DDevice.

Here is something if you want something that works even without a Capture Device connected and enabled. Save you some pain.

```python
from winsdk.windows.ai.machinelearning import LearningModelDevice, LearningModelDeviceKind
device  = LearningModelDevice(LearningModelDeviceKind.DIRECT_X_HIGH_PERFORMANCE)
```
Doesn't require the media device.

Should be an easy change, enjoy.

**Comment by Avasam** [comment]
Oh thanks! I'll try this asap!

**Comment by Avasam** [comment]
Seems to work. Not prefect because it still has a higher Windows version requirement (17763) than WGC itself (17134). But that's less likely to be an issue. Especially if I use both together.
