### ISSUE TITLE
Disable `Capture device:` dropdown when `Capture method:` is not `Video Capture Device`

### ISSUE THREAD

**Issue by Toufool** [Toufool/AutoSplit#196]
Self explanatory. I think this will avoid confusion. When it's disabled, maybe we can set the text to something like "Select video capture device above" or something. Kind of like this

![image](https://user-images.githubusercontent.com/37423484/213874375-52a9626f-2f0d-4c68-a5e4-7bfd8fcb1782.png)

And then when Video Capture Device is selected, we can enable the dropdown to select the device.

**Comment by Avasam** [comment]
I generally agree with the request for a design change here. But there's one critical issue the current design works around:
If a video device would cause extra lag(1) or cause an unrecoverable error(2) and is the default(3) then the "Video Capture Device" option becomes unusable.

---

1. Shouldn't be much of an issue with async device info. Was more of a problem during development. Could maybe cause the GV-USB2 to freeze?
2. Unfortunately OBS' own integrated Virtual Cam is such a case that causes an uncatchable hard crash with OpenCV.
3. I think it's better if there's a way for the user to select the capture device they wanna use before we try to use it.

We could unselect the capture device whenever a different capture method is selected. I doubt a regular user would often swap between them and need the capture device to be remembered. The your request can be implemented as-is.

**Comment by Toufool** [comment]
Functionality for this looks good.
