### ISSUE TITLE
Loop a set of images.

### ISSUE THREAD

**Issue by XeZey** [Toufool/AutoSplit#232]
**Is your feature request related to a problem? Please describe.**
The game Im currently making a loadless timer for, has 52 different levels which require two sets of two different images each time the level starts/ends for getting rid of loading times

**Describe the solution you'd like**
Most likely this could be done through UI.

**Describe alternatives you've considered**
adding these images every single time, which can be very annoying and take up quite a lot of time.

**Additional context**
making a set out of sets would be pretty cool also but probably not necessary.

**Comment by Avasam** [comment]
Thanks for the feature request! 

If you want to remove load times, I'd recommend a tool that can do it after the run in a robust manner (and can be re-run by verifiers as many times as they want). Even if AutoSplit supported it. 

---

Doing it within AutoSplit to at least approximate pause time while you're running is something I want too and is on my TODO list. I'll paste below some references to link the issues

https://github.com/Toufool/AutoSplit/pull/139#issuecomment-1284265349
> A proper solution, which I want to go for, seems to be to add proper support for loading screens or pause/unpause in AutoSplit. It would be running in parallel with the image comparison for splits.

#36 Is also a feature request that would require a UI change to represent the multiple images being compared
#234 Parallel pause images comparison. I just created this feature request.

If any of those two feature request would solve your needs in a satisfying manner, please go upvote them, and feel free to close this here issue in favor of those. If not, you can keep it open.

**Comment by XeZey** [comment]
> Doing it within AutoSplit to at least approximate pause time while you're running is something I want too and is on my TODO list. I'll paste below some references to link the the issues

From what I gathered so far, In the programs current state, removing loads while running live is already possible / essentially what I've done here. Of course this can also be used after the run as well. It might not be 100% accurate, but the game otherwise has massive load differences and removing load times manually is not really a viable option. Meaning so far, Ive basically accomplished everything I wanted to. So im not exactly sure what you mean by "todo" list, as in its already possible in the programs current state. It is pretty complex at the moment and you have to get creative with {b} {d},{pb},{bd} but its definitely achievable, especially if the game has very clear loading screens. For splitting you can use a "split" imagine with [0] and afterwards an immediate pause. maybe not "frame-accurate", but its enough for the game that Im running. though of course it would be nicer if both was possible

Either way, both of the issues you linked are very interesing.
