### ISSUE TITLE
SetHotkey buttons only set Start / Split

### ISSUE THREAD

**Issue by TalicZealot** [Toufool/AutoSplit#249]
## Description
All `Set Hotkey` buttons in the settings window write to the `Start / Split` field.

## Versions
- OS: Windows 10.0.19045
- AutoSplit: 2.1.0

## Context
I would guess something is going wrong around here: https://github.com/Toufool/AutoSplit/blob/dbf50f991270c222de7aef84afbc2f10267d963a/src/menu_bar.py#L245

**Comment by Avasam** [comment]
Fixed by #248 I wanted to release before this weekend but lacked the time. So it will go to after this NoReset x ComicCon event.
