### ISSUE TITLE
Discord Invite Invalid

### ISSUE THREAD

**Issue by Labreezy** [Toufool/AutoSplit#292]
I was unsure who to contact, I figure i raise an issue here.

**Describe the bug**
The discord server invite is no longer valid.

**To Reproduce**

1. Click on the discord invite link in the readme

**Expected behavior**
You join the discord through said invite

**Comment by Avasam** [comment]
Could you try clearing your browser cache? I once had a similar issue with another server preventing me from joining.
The invite https://discord.gg/Qcbxv9y should still be correct (I just tested it). You can also try pasting the invite link directly in discord: https://support.discord.com/hc/en-us/articles/360034842871-How-do-I-join-a-Server#h_01FSJF9GT2QJMS2PRAW36WNBS8
